spring:
  datasource:
    url: jdbc:mysql://prod-server:3306/CustomerProfile
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialectorg.hibernate.dialect.MySQLDialect
