spring:
  application:
    name: transaction-order

logging:
  level:
    com:
      transactionorder: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  file:
    name: logs/transaction-order.log
    path: ./logs


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 9090



